version: "3.2"

services:
    postgres:
        container_name: postgres
        image: postgres:14.4-alpine
        volumes:
            - postgres:/data/postgres
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "6543:5432"
        env_file:
            - ./.docker.env
        networks:
            - connect-backend
        restart: unless-stopped

networks:
    connect-backend:
        driver: bridge

 
volumes:
    postgres:
        driver: local